// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apirestful.Data;

#nullable disable

namespace apirestful.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241012211238_AddTableCustomers")]
    partial class AddTableCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("apirestful.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Descripcion 1 poderosa",
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descripcion 2 intrigrante",
                            Name = "Hogar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Descripcion 3 practica",
                            Name = "Ropa"
                        });
                });

            modelBuilder.Entity("apirestful.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("NumberContact")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("number_contact");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("apirestful.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("idCategory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IdCategory = 1,
                            Name = "Sleek Granite Mouse",
                            Price = 508.82999999999998,
                            Stock = 33
                        },
                        new
                        {
                            Id = 2,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IdCategory = 1,
                            Name = "Licensed Frozen Car",
                            Price = 519.01999999999998,
                            Stock = 57
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IdCategory = 3,
                            Name = "Ergonomic Concrete Bike",
                            Price = 798.44000000000005,
                            Stock = 49
                        },
                        new
                        {
                            Id = 4,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IdCategory = 3,
                            Name = "Generic Metal Ball",
                            Price = 981.53999999999996,
                            Stock = 16
                        },
                        new
                        {
                            Id = 5,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IdCategory = 2,
                            Name = "Intelligent Soft Soap",
                            Price = 881.61000000000001,
                            Stock = 48
                        });
                });

            modelBuilder.Entity("apirestful.Models.Product", b =>
                {
                    b.HasOne("apirestful.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
