// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apirestful.Data;

#nullable disable

namespace apirestful.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241010160017_se_agrega_la_tabla_Cateogry")]
    partial class se_agrega_la_tabla_Cateogry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("apirestful.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Descripcion 1 poderosa",
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descripcion 2 intrigrante",
                            Name = "Hogar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Descripcion 3 practica",
                            Name = "Ropa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
