// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apirestful.Data;

#nullable disable

namespace apirestful.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241012220355_alterIdCustomer")]
    partial class alterIdCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("apiRestFul.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasMaxLength(100)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("idCustomer");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("apirestful.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Descripcion 1 poderosa",
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descripcion 2 intrigrante",
                            Name = "Hogar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Descripcion 3 practica",
                            Name = "Ropa"
                        });
                });

            modelBuilder.Entity("apirestful.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("NumberContact")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("number_contact");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("apirestful.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int")
                        .HasColumnName("idCategory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IdCategory = 3,
                            Name = "Intelligent Wooden Pizza",
                            Price = 427.63,
                            Stock = 43
                        },
                        new
                        {
                            Id = 2,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IdCategory = 3,
                            Name = "Intelligent Wooden Fish",
                            Price = 916.77999999999997,
                            Stock = 32
                        },
                        new
                        {
                            Id = 3,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IdCategory = 2,
                            Name = "Handmade Steel Soap",
                            Price = 126.94,
                            Stock = 93
                        },
                        new
                        {
                            Id = 4,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IdCategory = 1,
                            Name = "Refined Concrete Pants",
                            Price = 935.34000000000003,
                            Stock = 23
                        },
                        new
                        {
                            Id = 5,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IdCategory = 1,
                            Name = "Handcrafted Rubber Towels",
                            Price = 443.35000000000002,
                            Stock = 94
                        });
                });

            modelBuilder.Entity("apiRestFul.Models.Order", b =>
                {
                    b.HasOne("apirestful.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("IdCustomer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("apirestful.Models.Product", b =>
                {
                    b.HasOne("apirestful.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
